# Generated by Django 5.1 on 2024-08-28 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volpi_api_agua', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AguaIngerida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd_agua', models.IntegerField(help_text='Informe a quantidade de água ingerida em ML')),
                ('data', models.DateField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volpi_api_agua.usuario')),
            ],
        ),
    ]
