# Generated by Django 4.2 on 2024-09-04 22:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('volpi_api_agua', '0002_aguaingerida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aguaingerida',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='aguaingerida',
            name='qtd_agua',
            field=models.IntegerField(help_text='Informe a quantidade de água ingerida em ML.'),
        ),
    ]
